theme: jekyll-theme-midnight
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: "Crime Busters Revival"
description: "Crime Busters Project"
gitorg: "https://github.com/VidhiKulkarni/crimebusters-revival"
google_analytics:
