theme: jekyll-theme-midnight
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: "Code Busters Revival"
gitorg: "https://github.com/lwu1822/crimebustersrevival"
google_analytics:
